# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpcapi_pb2 as grpcapi__pb2


class GrpcapiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/grpcapi.Grpcapi/Login',
                request_serializer=grpcapi__pb2.LoginRequest.SerializeToString,
                response_deserializer=grpcapi__pb2.LoginResponse.FromString,
                )
        self.GetAllOrder = channel.unary_unary(
                '/grpcapi.Grpcapi/GetAllOrder',
                request_serializer=grpcapi__pb2.GetAllOrderRequest.SerializeToString,
                response_deserializer=grpcapi__pb2.GetAllOrderResponse.FromString,
                )
        self.GetProductOrder = channel.unary_unary(
                '/grpcapi.Grpcapi/GetProductOrder',
                request_serializer=grpcapi__pb2.GetProductOrderRequest.SerializeToString,
                response_deserializer=grpcapi__pb2.GetProductOrderResponse.FromString,
                )


class GrpcapiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProductOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GrpcapiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=grpcapi__pb2.LoginRequest.FromString,
                    response_serializer=grpcapi__pb2.LoginResponse.SerializeToString,
            ),
            'GetAllOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllOrder,
                    request_deserializer=grpcapi__pb2.GetAllOrderRequest.FromString,
                    response_serializer=grpcapi__pb2.GetAllOrderResponse.SerializeToString,
            ),
            'GetProductOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductOrder,
                    request_deserializer=grpcapi__pb2.GetProductOrderRequest.FromString,
                    response_serializer=grpcapi__pb2.GetProductOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpcapi.Grpcapi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Grpcapi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpcapi.Grpcapi/Login',
            grpcapi__pb2.LoginRequest.SerializeToString,
            grpcapi__pb2.LoginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpcapi.Grpcapi/GetAllOrder',
            grpcapi__pb2.GetAllOrderRequest.SerializeToString,
            grpcapi__pb2.GetAllOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProductOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpcapi.Grpcapi/GetProductOrder',
            grpcapi__pb2.GetProductOrderRequest.SerializeToString,
            grpcapi__pb2.GetProductOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
