# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcapi.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgrpcapi.proto\x12\x07grpcapi\x1a\x1fgoogle/protobuf/timestamp.proto\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"2\n\rLoginResponse\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x14\n\x12GetAllOrderRequest\"\xbc\x02\n\x13GetAllOrderResponse\x12\x31\n\x05order\x18\x01 \x01(\x0b\x32\".grpcapi.GetAllOrderResponse.Order\x12\x15\n\rtotal_revenue\x18\x02 \x01(\x05\x12\x34\n\x10transaction_date\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x1a\xa4\x01\n\x05Order\x12\x10\n\x08order_no\x18\x01 \x01(\t\x12\x13\n\x0btotal_items\x18\x02 \x01(\x05\x12\x39\n\x06\x64\x65tail\x18\x03 \x01(\x0b\x32).grpcapi.GetAllOrderResponse.Order.Detail\x1a\x39\n\x06\x44\x65tail\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x05\"*\n\x16GetProductOrderRequest\x12\x10\n\x08order_no\x18\x01 \x01(\t\"\x95\x01\n\x17GetProductOrderResponse\x12\x10\n\x08order_no\x18\x01 \x01(\t\x12\x12\n\nid_product\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x05\x12\x13\n\x0btotal_order\x18\x05 \x01(\x05\x12\x13\n\x0btotal_price\x18\x06 \x01(\x05\x12\r\n\x05total\x18\x07 \x01(\x05\x32\xe1\x01\n\x07Grpcapi\x12\x36\n\x05Login\x12\x15.grpcapi.LoginRequest\x1a\x16.grpcapi.LoginResponse\x12H\n\x0bGetAllOrder\x12\x1b.grpcapi.GetAllOrderRequest\x1a\x1c.grpcapi.GetAllOrderResponse\x12T\n\x0fGetProductOrder\x12\x1f.grpcapi.GetProductOrderRequest\x1a .grpcapi.GetProductOrderResponseb\x06proto3')



_LOGINREQUEST = DESCRIPTOR.message_types_by_name['LoginRequest']
_LOGINRESPONSE = DESCRIPTOR.message_types_by_name['LoginResponse']
_GETALLORDERREQUEST = DESCRIPTOR.message_types_by_name['GetAllOrderRequest']
_GETALLORDERRESPONSE = DESCRIPTOR.message_types_by_name['GetAllOrderResponse']
_GETALLORDERRESPONSE_ORDER = _GETALLORDERRESPONSE.nested_types_by_name['Order']
_GETALLORDERRESPONSE_ORDER_DETAIL = _GETALLORDERRESPONSE_ORDER.nested_types_by_name['Detail']
_GETPRODUCTORDERREQUEST = DESCRIPTOR.message_types_by_name['GetProductOrderRequest']
_GETPRODUCTORDERRESPONSE = DESCRIPTOR.message_types_by_name['GetProductOrderResponse']
LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREQUEST,
  '__module__' : 'grpcapi_pb2'
  # @@protoc_insertion_point(class_scope:grpcapi.LoginRequest)
  })
_sym_db.RegisterMessage(LoginRequest)

LoginResponse = _reflection.GeneratedProtocolMessageType('LoginResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOGINRESPONSE,
  '__module__' : 'grpcapi_pb2'
  # @@protoc_insertion_point(class_scope:grpcapi.LoginResponse)
  })
_sym_db.RegisterMessage(LoginResponse)

GetAllOrderRequest = _reflection.GeneratedProtocolMessageType('GetAllOrderRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETALLORDERREQUEST,
  '__module__' : 'grpcapi_pb2'
  # @@protoc_insertion_point(class_scope:grpcapi.GetAllOrderRequest)
  })
_sym_db.RegisterMessage(GetAllOrderRequest)

GetAllOrderResponse = _reflection.GeneratedProtocolMessageType('GetAllOrderResponse', (_message.Message,), {

  'Order' : _reflection.GeneratedProtocolMessageType('Order', (_message.Message,), {

    'Detail' : _reflection.GeneratedProtocolMessageType('Detail', (_message.Message,), {
      'DESCRIPTOR' : _GETALLORDERRESPONSE_ORDER_DETAIL,
      '__module__' : 'grpcapi_pb2'
      # @@protoc_insertion_point(class_scope:grpcapi.GetAllOrderResponse.Order.Detail)
      })
    ,
    'DESCRIPTOR' : _GETALLORDERRESPONSE_ORDER,
    '__module__' : 'grpcapi_pb2'
    # @@protoc_insertion_point(class_scope:grpcapi.GetAllOrderResponse.Order)
    })
  ,
  'DESCRIPTOR' : _GETALLORDERRESPONSE,
  '__module__' : 'grpcapi_pb2'
  # @@protoc_insertion_point(class_scope:grpcapi.GetAllOrderResponse)
  })
_sym_db.RegisterMessage(GetAllOrderResponse)
_sym_db.RegisterMessage(GetAllOrderResponse.Order)
_sym_db.RegisterMessage(GetAllOrderResponse.Order.Detail)

GetProductOrderRequest = _reflection.GeneratedProtocolMessageType('GetProductOrderRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPRODUCTORDERREQUEST,
  '__module__' : 'grpcapi_pb2'
  # @@protoc_insertion_point(class_scope:grpcapi.GetProductOrderRequest)
  })
_sym_db.RegisterMessage(GetProductOrderRequest)

GetProductOrderResponse = _reflection.GeneratedProtocolMessageType('GetProductOrderResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETPRODUCTORDERRESPONSE,
  '__module__' : 'grpcapi_pb2'
  # @@protoc_insertion_point(class_scope:grpcapi.GetProductOrderResponse)
  })
_sym_db.RegisterMessage(GetProductOrderResponse)

_GRPCAPI = DESCRIPTOR.services_by_name['Grpcapi']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOGINREQUEST._serialized_start=59
  _LOGINREQUEST._serialized_end=109
  _LOGINRESPONSE._serialized_start=111
  _LOGINRESPONSE._serialized_end=161
  _GETALLORDERREQUEST._serialized_start=163
  _GETALLORDERREQUEST._serialized_end=183
  _GETALLORDERRESPONSE._serialized_start=186
  _GETALLORDERRESPONSE._serialized_end=502
  _GETALLORDERRESPONSE_ORDER._serialized_start=338
  _GETALLORDERRESPONSE_ORDER._serialized_end=502
  _GETALLORDERRESPONSE_ORDER_DETAIL._serialized_start=445
  _GETALLORDERRESPONSE_ORDER_DETAIL._serialized_end=502
  _GETPRODUCTORDERREQUEST._serialized_start=504
  _GETPRODUCTORDERREQUEST._serialized_end=546
  _GETPRODUCTORDERRESPONSE._serialized_start=549
  _GETPRODUCTORDERRESPONSE._serialized_end=698
  _GRPCAPI._serialized_start=701
  _GRPCAPI._serialized_end=926
# @@protoc_insertion_point(module_scope)
